import QtQuick 2.0

// NOTE: https://doc.qt.io/qt-5/qml-color.html#svg-color-reference
ListModel {

    ListElement { themeName: "aliceblue"; themeColor: "#f0f8ff" ; }
    ListElement { themeName: "antiquewhite"; themeColor: "#faebd7" ; }
    ListElement { themeName: "aqua"; themeColor: "#00ffff" ; }
    ListElement { themeName: "aquamarine"; themeColor: "#7fffd4" ; }
    ListElement { themeName: "azure"; themeColor: "#f0ffff" ; }
    ListElement { themeName: "beige"; themeColor: "#f5f5dc" ; }
    ListElement { themeName: "bisque"; themeColor: "#ffe4c4" ; }
    ListElement { themeName: "black"; themeColor: "#000000" ; }
    ListElement { themeName: "blanchedalmond"; themeColor: "#ffebcd" ; }
    ListElement { themeName: "blue"; themeColor: "#0000ff" ; }
    ListElement { themeName: "blueviolet"; themeColor: "#8a2be2" ; }
    ListElement { themeName: "brown"; themeColor: "#a52a2a" ; }
    ListElement { themeName: "burlywood"; themeColor: "#deb887" ; }
    ListElement { themeName: "cadetblue"; themeColor: "#5f9ea0" ; }
    ListElement { themeName: "chartreuse"; themeColor: "#7fff00" ; }
    ListElement { themeName: "chocolate"; themeColor: "#d2691e" ; }
    ListElement { themeName: "coral"; themeColor: "#ff7f50" ; }
    ListElement { themeName: "cornflowerblue"; themeColor: "#6495ed" ; }
    ListElement { themeName: "cornsilk"; themeColor: "#fff8dc" ; }
    ListElement { themeName: "crimson"; themeColor: "#dc143c" ; }
    ListElement { themeName: "cyan"; themeColor: "#00ffff" ; }
    ListElement { themeName: "darkblue"; themeColor: "#00008b" ; }
    ListElement { themeName: "darkcyan"; themeColor: "#008b8b" ; }
    ListElement { themeName: "darkgoldenrod"; themeColor: "#b8860b" ; }
    ListElement { themeName: "darkgray"; themeColor: "#a9a9a9" ; }
    ListElement { themeName: "darkgreen"; themeColor: "#006400" ; }
    ListElement { themeName: "darkgrey"; themeColor: "#a9a9a9" ; }
    ListElement { themeName: "darkkhaki"; themeColor: "#bdb76b" ; }
    ListElement { themeName: "darkmagenta"; themeColor: "#8b008b" ; }
    ListElement { themeName: "darkolivegreen"; themeColor: "#556b2f" ; }
    ListElement { themeName: "darkorange"; themeColor: "#ff8c00" ; }
    ListElement { themeName: "darkorchid"; themeColor: "#9932cc" ; }
    ListElement { themeName: "darkred"; themeColor: "#8b0000" ; }
    ListElement { themeName: "darksalmon"; themeColor: "#e9967a" ; }
    ListElement { themeName: "darkseagreen"; themeColor: "#8fbc8f" ; }
    ListElement { themeName: "darkslateblue"; themeColor: "#483d8b" ; }
    ListElement { themeName: "darkslategray"; themeColor: "#2f4f4f" ; }
    ListElement { themeName: "darkslategrey"; themeColor: "#2f4f4f" ; }
    ListElement { themeName: "darkturquoise"; themeColor: "#00ced1" ; }
    ListElement { themeName: "darkviolet"; themeColor: "#9400d3" ; }
    ListElement { themeName: "deeppink"; themeColor: "#ff1493" ; }
    ListElement { themeName: "deepskyblue"; themeColor: "#00bfff" ; }
    ListElement { themeName: "dimgray"; themeColor: "#696969" ; }
    ListElement { themeName: "dimgrey"; themeColor: "#696969" ; }
    ListElement { themeName: "dodgerblue"; themeColor: "#1e90ff" ; }
    ListElement { themeName: "firebrick"; themeColor: "#b22222" ; }
    ListElement { themeName: "floralwhite"; themeColor: "#fffaf0" ; }
    ListElement { themeName: "forestgreen"; themeColor: "#228b22" ; }
    ListElement { themeName: "fuchsia"; themeColor: "#ff00ff" ; }
    ListElement { themeName: "gainsboro"; themeColor: "#dcdcdc" ; }
    ListElement { themeName: "ghostwhite"; themeColor: "#f8f8ff" ; }
    ListElement { themeName: "gold"; themeColor: "#ffd700" ; }
    ListElement { themeName: "goldenrod"; themeColor: "#daa520" ; }
    ListElement { themeName: "gray"; themeColor: "#808080" ; }
    ListElement { themeName: "grey"; themeColor: "#808080" ; }
    ListElement { themeName: "green"; themeColor: "#008000" ; }
    ListElement { themeName: "greenyellow"; themeColor: "#adff2f" ; }
    ListElement { themeName: "honeydew"; themeColor: "#f0fff0" ; }
    ListElement { themeName: "hotpink"; themeColor: "#ff69b4" ; }
    ListElement { themeName: "indianred"; themeColor: "#cd5c5c" ; }
    ListElement { themeName: "indigo"; themeColor: "#4b0082" ; }
    ListElement { themeName: "ivory"; themeColor: "#fffff0" ; }
    ListElement { themeName: "khaki"; themeColor: "#f0e68c" ; }
    ListElement { themeName: "lavender"; themeColor: "#e6e6fa" ; }
    ListElement { themeName: "lavenderblush"; themeColor: "#fff0f5" ; }
    ListElement { themeName: "lawngreen"; themeColor: "#7cfc00" ; }
    ListElement { themeName: "lemonchiffon"; themeColor: "#fffacd" ; }
    ListElement { themeName: "lightblue"; themeColor: "#add8e6" ; }
    ListElement { themeName: "lightcoral"; themeColor: "#f08080" ; }
    ListElement { themeName: "lightcyan"; themeColor: "#e0ffff" ; }
    ListElement { themeName: "lightgoldenrodyellow"; themeColor: "#fafad2" ; }
    ListElement { themeName: "lightgray"; themeColor: "#d3d3d3" ; }
    ListElement { themeName: "lightgreen"; themeColor: "#90ee90" ; }
    ListElement { themeName: "lightgrey"; themeColor: "#d3d3d3" ; }
    ListElement { themeName: "lightpink"; themeColor: "#ffb6c1" ; }
    ListElement { themeName: "lightsalmon"; themeColor: "#ffa07a" ; }
    ListElement { themeName: "lightseagreen"; themeColor: "#20b2aa" ; }
    ListElement { themeName: "lightskyblue"; themeColor: "#87cefa" ; }
    ListElement { themeName: "lightslategray"; themeColor: "#778899" ; }
    ListElement { themeName: "lightslategrey"; themeColor: "#778899" ; }
    ListElement { themeName: "lightsteelblue"; themeColor: "#b0c4de" ; }
    ListElement { themeName: "lightyellow"; themeColor: "#ffffe0" ; }
    ListElement { themeName: "lime"; themeColor: "#00ff00" ; }
    ListElement { themeName: "limegreen"; themeColor: "#32cd32" ; }
    ListElement { themeName: "linen"; themeColor: "#faf0e6" ; }
    ListElement { themeName: "magenta"; themeColor: "#ff00ff" ; }
    ListElement { themeName: "maroon"; themeColor: "#800000" ; }
    ListElement { themeName: "mediumaquamarine"; themeColor: "#66cdaa" ; }
    ListElement { themeName: "mediumblue"; themeColor: "#0000cd" ; }
    ListElement { themeName: "mediumorchid"; themeColor: "#ba55d3" ; }
    ListElement { themeName: "mediumpurple"; themeColor: "#9370db" ; }
    ListElement { themeName: "mediumseagreen"; themeColor: "#3cb371" ; }
    ListElement { themeName: "mediumslateblue"; themeColor: "#7b68ee" ; }
    ListElement { themeName: "mediumspringgreen"; themeColor: "#00fa9a" ; }
    ListElement { themeName: "mediumturquoise"; themeColor: "#48d1cc" ; }
    ListElement { themeName: "mediumvioletred"; themeColor: "#c71585" ; }
    ListElement { themeName: "midnightblue"; themeColor: "#191970" ; }
    ListElement { themeName: "mintcream"; themeColor: "#f5fffa" ; }
    ListElement { themeName: "mistyrose"; themeColor: "#ffe4e1" ; }
    ListElement { themeName: "moccasin"; themeColor: "#ffe4b5" ; }
    ListElement { themeName: "navajowhite"; themeColor: "#ffdead" ; }
    ListElement { themeName: "navy"; themeColor: "#000080" ; }
    ListElement { themeName: "oldlace"; themeColor: "#fdf5e6" ; }
    ListElement { themeName: "olive"; themeColor: "#808000" ; }
    ListElement { themeName: "olivedrab"; themeColor: "#6b8e23" ; }
    ListElement { themeName: "orange"; themeColor: "#ffa500" ; }
    ListElement { themeName: "orangered"; themeColor: "#ff4500" ; }
    ListElement { themeName: "orchid"; themeColor: "#da70d6" ; }
    ListElement { themeName: "palegoldenrod"; themeColor: "#eee8aa" ; }
    ListElement { themeName: "palegreen"; themeColor: "#98fb98" ; }
    ListElement { themeName: "paleturquoise"; themeColor: "#afeeee" ; }
    ListElement { themeName: "palevioletred"; themeColor: "#db7093" ; }
    ListElement { themeName: "papayawhip"; themeColor: "#ffefd5" ; }
    ListElement { themeName: "peachpuff"; themeColor: "#ffdab9" ; }
    ListElement { themeName: "peru"; themeColor: "#cd853f" ; }
    ListElement { themeName: "pink"; themeColor: "#ffc0cb" ; }
    ListElement { themeName: "plum"; themeColor: "#dda0dd" ; }
    ListElement { themeName: "powderblue"; themeColor: "#b0e0e6" ; }
    ListElement { themeName: "purple"; themeColor: "#800080" ; }
    ListElement { themeName: "red"; themeColor: "#ff0000" ; }
    ListElement { themeName: "rosybrown"; themeColor: "#bc8f8f" ; }
    ListElement { themeName: "royalblue"; themeColor: "#4169e1" ; }
    ListElement { themeName: "saddlebrown"; themeColor: "#8b4513" ; }
    ListElement { themeName: "salmon"; themeColor: "#fa8072" ; }
    ListElement { themeName: "sandybrown"; themeColor: "#f4a460" ; }
    ListElement { themeName: "seagreen"; themeColor: "#2e8b57" ; }
    ListElement { themeName: "seashell"; themeColor: "#fff5ee" ; }
    ListElement { themeName: "sienna"; themeColor: "#a0522d" ; }
    ListElement { themeName: "silver"; themeColor: "#c0c0c0" ; }
    ListElement { themeName: "skyblue"; themeColor: "#87ceeb" ; }
    ListElement { themeName: "slateblue"; themeColor: "#6a5acd" ; }
    ListElement { themeName: "slategray"; themeColor: "#708090" ; }
    ListElement { themeName: "slategrey"; themeColor: "#708090" ; }
    ListElement { themeName: "snow"; themeColor: "#fffafa" ; }
    ListElement { themeName: "springgreen"; themeColor: "#00ff7f" ; }
    ListElement { themeName: "steelblue"; themeColor: "#4682b4" ; }
    ListElement { themeName: "tan"; themeColor: "#d2b48c" ; }
    ListElement { themeName: "teal"; themeColor: "#008080" ; }
    ListElement { themeName: "thistle"; themeColor: "#d8bfd8" ; }
    ListElement { themeName: "tomato"; themeColor: "#ff6347" ; }
    ListElement { themeName: "turquoise"; themeColor: "#40e0d0" ; }
    ListElement { themeName: "violet"; themeColor: "#ee82ee" ; }
    ListElement { themeName: "wheat"; themeColor: "#f5deb3" ; }
    ListElement { themeName: "white"; themeColor: "#ffffff" ; }
    ListElement { themeName: "whitesmoke"; themeColor: "#f5f5f5" ; }
    ListElement { themeName: "yellow"; themeColor: "#ffff00" ; }
    ListElement { themeName: "yellowgreen"; themeColor: "#9acd32" ; }

}
